#!/usr/bin/env ruby

require "fileutils"
require "pathname"

gemspecs = Dir.glob("*.gemspec")
exit unless gemspecs.size == 1

gemspec = Pathname.new(gemspecs.first)
exit unless gemspec.exist?

tempversion = Pathname.new("lib/.version/version.rb")
exit unless tempversion.exist?

requires = []
gemspec.each_line do |line|
  next unless line =~ /^\s*require\s+['"]([\w\/-]+)['"]\s*$/

  requires << $1
end

version_requires = requires.grep(/\/version$/)
exit unless version_requires.size == 1

target = Pathname.new("lib/#{version_requires.first}.rb")
exit if target.exist?

FileUtils.mkdir_p target.dirname

FileUtils.mv tempversion, target
